[package]
name = "pineappleblaster/linq-luau"
description = "A typed, lazy, chainable query API for Luau collections."
version = "0.4.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
authors = [
    "McRocketNuggets"
]
repository = "https://github.com/PineappleBlaster/linq-luau"

[dependencies]
